package com.jumpstart.food_ordering_system.entity;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@Table(name = "category")
public class Food_categories {// entity class to represent the db table

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//autogenerated id
    private int id;

    @Column(nullable = false)// cannot have the food ordered name as null
    private String name;



    public Food_categories(String name) {
        this.name = name;
    }
}
